baseURL = "https://roughconsensus.nl/"
languageCode = "en-us"
title = "Rough Consensus"
theme = "hugo-now-ui"
googleAnalytics = "UA-7840077-4"

[permalinks]
post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "What I do"
    url = "/#what-i-do"
    pre = "<i class='now-ui-icons business_bulb-63'></i>"
    weight = 1
[[menu.main]]
    name = "How I work"
    url = "/#how-i-work"
    pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
    weight = 2
[[menu.main]]
    name = "About me"
    url = "/#about-me"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 3
[[menu.main]]
    name = "About the name"
    url = "/#about"
    pre = "<i class='now-ui-icons travel_info'></i>"
    weight = 4
[[menu.main]]
    name = "Can I help you?"
    url = "/#can-i-help-you"
    pre = "<i class='now-ui-icons ui-1_email-85'></i>"
    weight = 5

[[menu.footer]]
    identifier = "phone"
    name = "+31 646 337 993"
    pre = "<i class='now-ui-icons tech_mobile'></i>"
    url = "/phone/"
    weight = 1
[[menu.footer]]
    identifier = "email"
    name = "michiel@roughconsensus.nl"
    pre = "<i class='now-ui-icons ui-1_email-85'></i>"
    url = "mailto:michiel@roughconsensus.nl"
    weight = 2
[[menu.footer]]
    identifier = "kvk"
    name = "KVK 67149596"
    pre = "<i class='fa fa-briefcase'></i>"
    url = "https://www.kvk.nl/zoeken/?q=67149596"
    weight = 3
[[menu.footer]]
    identifier = "copyright"
    name = "CC BY-NC-ND 4.0"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
    weight = 4

[params]
    background = "/img/header.jpg"
    logo = "/img/logo.png"
    tint = "green"
    custom_css = ['/css/custom.css']
    custom_js = ['custom.js']
    date_format = "Mon 2 Jan 2006"
    description = "Accelerate your digital transformation."
